version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo:4.4.6
    network_mode: "host"
    ports:
      - 27017:21017
    restart: always

  develop:
    build: .
    container_name: honey-store-backend-develop
    network_mode: "host"
    env_file: .env
    ports:
      - 3000:3000
    restart: always

  
