version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo:4.4.6
    network_mode: "host"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: password
        MONGO_INITDB_DATABASE: honey-store-backend
    restart: always

  redis:
    container_name: redis
    image: 'redis:latest'
    network_mode: "host"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always

  backend:
    container_name: honey-store-backend-production
    image: aliabdi709/honey-backend:0.0.3
    network_mode: "host"
    env_file: .env
    volumes:
      - honey-upload:/usr/src/app/upload
    restart: always

volumes:
  mongo-data:
    external: false
  honey-upload:
    external: false
  redis-data:
    external: false