export const Message = {
    ERROR_OCCURRED: () => "خطایی رخ داده است",
    INVALID_MONGO_ID: (name  = '') => `شناسه ${name} به درستی وارد نشده است`,
    INCORRECT: (name: string) => `${name} به درستی وارد نشده است`,
    INCORRECT_FORMAT: (name: string) => `فرمت ${name} اشتباه است`,
    MUST_BE_STRING: (name: string) => `${name} باید به صورت حروف وارد شود`,
    MUST_BE_NUMBER: (name: string) => `${name} باید به صورت عدد وارد شود`,
    MUST_BE_ARRAY: (name: string) => `${name} باید به صورت آرایه وارد شود`,
    NOT_BE_EMPTY: (name: string) => `${name} نمی تواند خالی باشد`,
    SHOULD_BE_DEFINED: (name: string) => `${name} باید تعریف شود`,
    WEAK: (name: string) => `${name} ضعیف است`,
    SUCCESS: () => `درخواست انجام شد`,
    MINIMUM_STRING: (name: string, min: number) => `${name} نباید کمتر از ${min} حرف باشد`,
    MINIMUM_NUMBER: (name: string, min: number) => `${name} نباید کمتر از ${min} باشد`,
    MAXIMUM_STRING: (name: string, max: number) => `${name} نباید بیشتر از ${max} حرف باشد`,
    MAXIMUM_NUMBER: (name: string, max: number) => `${name} نباید بیشتر از ${max} باشد`,
    MAXIMUM_VOLUME_FILE: (name: string, max: number) => `حجم فایل ${name} نباید بیشتر از ${max} باشد`,
    NOT_MATCH: () =>  'تایید پسورد و پسورد با هم مطابقت ندارند',
    INVALID_PHONE_OR_PASSWORD: () => 'شماره تماس یا پسورد اشتباه است',
    ALREADY_EXIST: (name: string) => `${name} در سیستم وجود دارد`,
    NOT_EXIST: (name: string) => `${name} در سیستم وجود ندارد`,
    AMOUNTIS_LESS_1000: () => `مبلغ کمتر از 1000 است`,
    NOT_ENOUGH_PRODUCT: (name: string) => `محصول ${name} به این تعداد درخواستی موجود نمی باشد. سبد خریدتان را ویرایش کنید`,
    PRODUCT_EXIST_IN: (name: string) => `محصول در ${name} کاربران وجود دارد. نمی توانید حذف کنید.`,
}