export const Message = {
    INVALID_MONGO_ID: (name : string = ''): string => `شناسه ${name} به درستی وارد نشده است`,
    INCORRECT: (name: string): string => `${name} به درستی وارد نشده است`,
    INCORRECT_FORMAT: (name: string): string => `فرمت ${name} اشتباه است`,
    MUST_BE_STRING: (name: string): string => `${name} باید به صورت حروف وارد شود`,
    MUST_BE_NUMBER: (name: string): string => `${name} باید به صورت عدد وارد شود`,
    MUST_BE_ARRAY: (name: string): string => `${name} باید به صورت آرایه وارد شود`,
    NOT_BE_EMPTY: (name: string): string => `${name} نمی تواند خالی باشد`,
    SHOULD_BE_DEFINED: (name: string): string => `${name} باید تعریف شود`,
    WEAK: (name: string): string => `${name} ضعیف است`,
    SUCCESS: (): string => `درخواست انجام شد`,
    MINIMUM_STRING: (name: string, min: number): string => `${name} نباید کمتر از ${min} حرف باشد`,
    MAXIMUM_STRING: (name: string, max: number): string => `${name} نباید بیشتر از ${max} حرف باشد`,
    MAXIMUM_VOLUME_FILE: (name: string, max: number): string => `حجم فایل ${name} نباید بیشتر از ${max} باشد`,
    NOT_MATCH: (): string =>  'تایید پسورد و پسورد با هم مطابقت ندارند',
    INVALID_PHONE_OR_PASSWORD: (): string => 'شماره تماس یا پسورد اشتباه است',
    ALREADY_EXIST: (name: string): string => `${name} در سیستم وجود دارد`,
}