export const Name = {
    PRODUCT: 'محصول',
    USER: 'کاربر',
    NAME: 'نام',
    IMAGE_SRC: 'آدرس تصویر',
    QUANTITY: 'تعداد',
    PRICE: 'قیمت',
    DISCOUNT: 'تخفیف',
    CATEGORY: 'دسته',
    CODE: 'کد',
    DESCRIPTION: 'توضیحات',
    LAST_NAME: 'نام خانوادگی',
    IP: 'ip',
    PHONE_NUMBER: 'شماره موبایل',
    EMAIL: 'ایمیل',
    PASSWORD: 'پسورد',
    NEW_PASSWORD: 'پسورد جدید',
    PASSWORD_CONFIRM: 'تایید پسورد', 
    NEW_PASSWORD_CONFIRM: 'تایید پسورد جدید', 
    ADDRESS: 'آدرس',
    POSTAL_ADDRESS: 'آدرس پستی',
    POSTAL_CODE: 'کد پستی',
    CITY: 'شهر',
    ID: 'شناسه',
    PRODUCT_ID: 'شناسه محصول',
    COMMENT_ID: 'شناسه نظر',
    FILE: 'فایل',
    PROVINCE: 'استان',
    PLAQUE: 'پلاک',
    RECIPIENT: 'گیرنده',
    RECIPIENT_NAME: 'نام گیرنده',
    RECIPIENT_LAST_NAME: 'نام خانوادگی گیرنده',
    RECIPIENT_PHONE_NUMBER: 'شماره تلفن گیرنده',
    LABEL: "برچسب",
    TYPE: "نوع",
    UNIT: "واحد",
    PROPERTIES: "خصوصیات",
    COMMENT: "کامنت",
    TITLE: "عنوان",
    TEXT: "متن",
    SCORE: "امتیاز",
    CART: "سبد خرید",
    STATUS: "وضعیت",
    ORDER: "سفارش",
    SORT: "مرتب سازی",
    DELETED_AT: "حذف",
    USER_OR_PASS: "شماره تلفن یا پسورد",
}