export const Name = {
    PRODUCT: 'محصول',
    USER: 'کاربر',
    NAME: 'نام',
    IMAGE_SRC: 'آدرس تصویر',
    QUANTITY: 'تعداد',
    PRICE: 'قیمت',
    DISCOUNT: 'تخفیف',
    CATEGORY: 'دسته',
    CODE: 'کد',
    DESCRIPTION: 'توضیحات',
    LAST_NAME: 'نام خانوادگی',
    IP: 'ip',
    PHONE_NUMBER: 'شماره موبایل',
    EMAIL: 'ایمیل',
    PASSWORD: 'پسورد',
    PASSWORD_CONFIRM: 'تایید پسورد', 
    ADDRESS: 'آدرس',
    POSTAL_ADDRESS: 'آدرس پستی',
    POSTAL_CODE: 'کد پستی',
    CITY: 'شهر',
    ID: 'شناسه',
    FILE: 'فایل',
    PROVINCE: 'استان',
    PLAQUE: 'پلاک',
    RECIPIENT: 'گیرنده',
    RECIPIENT_NAME: 'نام گیرنده',
    RECIPIENT_LAST_NAME: 'نام خانوادگی گیرنده',
    RECIPIENT_PHONE_NUMBER: 'شماره تلفن گیرنده',
    LABEL: "برچسب",
    TYPE: "نوع",
    UNIT: "واحد",
    PROPERTIES: "خصوصیات",
}