export const Name = {
    PRODUCT: 'محصول',
    USER: 'کاربر',
    NAME: 'نام',
    IMAGE_SRC: 'آدرس تصویر',
    QUANTITY: 'تعداد',
    PRICE: 'قیمت',
    DISCOUNT: 'تخفیف',
    CATEGORY: 'دسته',
    CODE: 'کد',
    DESCRIPTION: 'توضیحات',
    LAST_NAME: 'نام خانوادگی',
    IP: 'ip',
    PHONE_NUMBER: 'شماره موبایل',
    EMAIL: 'ایمیل',
    PASSWORD: 'پسورد',
    PASSWORD_CONFIRM: 'تایید پسورد', 
    ADDRESS: 'آدرس',
    POSTAL_CODE: 'کد پستی',
    CITY: 'شهر',
    ID: 'شناسه',
    FILE: 'فایل',
}